import { useState, useRef, useEffect, useCallback } from "react";
import { Button } from "primereact/button";
import { InputText } from "primereact/inputtext";
import { Dropdown } from "primereact/dropdown";
import { Dialog } from "primereact/dialog";
import { Toast } from "primereact/toast";
import { InputMask } from "primereact/inputmask";
import { Card } from "primereact/card";
import { Calendar } from "primereact/calendar";
import { AutoComplete } from "primereact/autocomplete";
import { Paginator } from "primereact/paginator";
import api from "../services/api/axios";
import "../styles/employees.css";

/**
 * Employees Component
 * Enterprise-grade employee management with:
 * - Complete employee form with all required fields
 * - Country dropdown with all countries
 * - Phone number with country code
 * - PrimeReact DataTable for employee listing
 * - Add/Edit/Delete operations with dialog popup
 */
export default function Employees() {
  // Country list (sample - add more as needed)
  const countries = [
    { name: "India", code: "IN", dialCode: "+91" },
    { name: "United States", code: "US", dialCode: "+1" },
    { name: "United Kingdom", code: "GB", dialCode: "+44" },
    { name: "Canada", code: "CA", dialCode: "+1" },
    { name: "Australia", code: "AU", dialCode: "+61" },
    { name: "Germany", code: "DE", dialCode: "+49" },
    { name: "France", code: "FR", dialCode: "+33" },
    { name: "Japan", code: "JP", dialCode: "+81" },
    { name: "China", code: "CN", dialCode: "+86" },
    { name: "Brazil", code: "BR", dialCode: "+55" },
    { name: "Mexico", code: "MX", dialCode: "+52" },
    { name: "Singapore", code: "SG", dialCode: "+65" },
    { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
    { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
    { name: "South Africa", code: "ZA", dialCode: "+27" },
  ];

  // Employee roles
  const roles = [
    { label: "Admin", value: "admin" },
    { label: "Manager", value: "manager" },
    { label: "Cashier", value: "cashier" },
    { label: "Stock Keeper", value: "stock_keeper" },
    { label: "Sales Representative", value: "sales_rep" },
    { label: "Supervisor", value: "supervisor" },
  ];

  // Employee form state (matches backend Employee model)
  const [employeeForm, setEmployeeForm] = useState({
    // emp_id auto-generated by backend starting from 1000
    name: "",
    email: "",
    countryCode: countries[0],
    phone_number: "",
    aadhar_number: "",
    address: "",
    city: "",
    state: "",
    country: null,
    role: null,
    joining_date: null,
    password: "", // Required for creating new employee
  });

  // Form validation errors (displayed in dialog, not toast)
  const [formErrors, setFormErrors] = useState({});

  // UI state (matches backend Employee schema)
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(false);
  const [totalRecords, setTotalRecords] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [customFieldLabels, setCustomFieldLabels] = useState([]);

  const [dialogVisible, setDialogVisible] = useState(false);
  const [viewDialogVisible, setViewDialogVisible] = useState(false);
  const [viewingEmployee, setViewingEmployee] = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [filterField, setFilterField] = useState(null);
  const [filterValue, setFilterValue] = useState("");
  const toast = useRef(null);

  // Custom Labels state for employee dialog
  const [employeeLabels, setEmployeeLabels] = useState([]);

  // Custom Label Definition Dialog state
  const [customLabelDialogVisible, setCustomLabelDialogVisible] =
    useState(false);
  const [newLabelName, setNewLabelName] = useState("");
  const [newLabelValues, setNewLabelValues] = useState([""]);

  // Deprecated AutoComplete suggestion state (not used with Dropdown)
  // const [labelNameSuggestions, setLabelNameSuggestions] = useState([]);
  // const [labelValueSuggestions, setLabelValueSuggestions] = useState([]);

  // Predefined common label names
  const commonLabelNames = [
    "Emergency Contact",
    "Blood Group",
    "Department",
    "Reporting Manager",
    "Work Location",
    "Employee Type",
    "Skills",
    "Certification",
    "Languages Known",
    "Previous Company",
    "Size",
  ];

  // Predefined values for specific label names (stateful to allow custom additions)
  const [labelValueMappings, setLabelValueMappings] = useState({
    Size: ["XL", "L", "M", "S", "XS"],
    "Blood Group": ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
    "Employee Type": ["Full-Time", "Part-Time", "Contract", "Intern"],
  });

  // Build label name options from predefined + custom defined + existing employee labels
  const labelNameOptions = [
    ...commonLabelNames.map((n) => ({ label: n, value: n })),
    // Add custom defined labels from labelValueMappings that aren't in commonLabelNames
    ...Object.keys(labelValueMappings)
      .filter((key) => !commonLabelNames.includes(key))
      .map((key) => ({ label: key, value: key })),
    // Add labels from existing employees that aren't already included
    ...new Set(
      employees
        .flatMap((e) => e.custom_fields || [])
        .flatMap((fieldObj) => Object.keys(fieldObj))
        .filter(Boolean)
        .filter((n) => !commonLabelNames.includes(n) && !labelValueMappings[n])
    ),
  ].map((n) => (typeof n === "string" ? { label: n, value: n } : n));

  // Note: labelValueOptions replaced by getLabelValueOptions() for dynamic mapping

  // Filter options for dropdown (matches backend Employee fields + custom fields)
  const getFilterOptions = () => {
    const baseOptions = [
      { label: "Employee ID", value: "emp_id" },
      { label: "Employee Name", value: "name" },
      { label: "Email", value: "email" },
      { label: "Phone Number", value: "phone_number" },
      { label: "Aadhar Number", value: "aadhar_number" },
      { label: "City", value: "city" },
      { label: "State", value: "state" },
      { label: "Country", value: "country" },
      { label: "Role", value: "role" },
    ];

    // Add custom field labels as filter options from backend
    const customFieldOptions = customFieldLabels.map((label) => ({
      label: label,
      value: `custom_${label}`,
    }));

    return [...baseOptions, ...customFieldOptions];
  };

  // Form field change handler
  const handleChange = (field, value) => {
    setEmployeeForm((prev) => ({ ...prev, [field]: value }));
  };

  // Fetch employees from backend with pagination
  const fetchEmployees = useCallback(
    async (page = currentPage, limit = rowsPerPage) => {
      try {
        setLoading(true);
        const skip = page * limit;

        // Build URL with query parameters
        let url = `/employees?skip=${skip}&limit=${limit}`;
        if (filterField && filterValue.trim()) {
          url += `&filter_field=${encodeURIComponent(
            filterField
          )}&filter_value=${encodeURIComponent(filterValue)}`;
        }

        const response = await api.get(url);

        // Handle paginated response from backend
        if (response.data.items && Array.isArray(response.data.items)) {
          setEmployees(response.data.items);
          setTotalRecords(response.data.total || 0);
        } else {
          // Fallback for non-paginated response (shouldn't happen)
          setEmployees(response.data);
          setTotalRecords(response.data.length);
        }
      } catch (error) {
        console.error("Error fetching employees:", error);

        let errorMessage = "Failed to load employees";

        if (error.response?.status === 401) {
          errorMessage = "Session expired. Please login again.";
        } else if (error.response?.status === 403) {
          errorMessage =
            "Access denied. You don't have permission to view employees.";
        } else if (error.response?.data?.detail) {
          errorMessage =
            typeof error.response.data.detail === "string"
              ? error.response.data.detail
              : "Failed to load employees";
        }

        toast.current?.show({
          severity: "error",
          summary: "Error",
          detail: errorMessage,
          life: 4000,
        });

        // If unauthorized, clear employees list
        if (error.response?.status === 401 || error.response?.status === 403) {
          setEmployees([]);
        }
      } finally {
        setLoading(false);
      }
    },
    [currentPage, rowsPerPage, filterField, filterValue]
  );

  // Fetch custom field labels from backend
  const fetchCustomFieldLabels = useCallback(async () => {
    try {
      const response = await api.get("/employees/custom-fields/labels");
      setCustomFieldLabels(response.data || []);
    } catch (error) {
      console.error("Error fetching custom field labels:", error);
      // Silently fail - custom fields are optional
    }
  }, []);

  // Load employees and custom field labels on component mount
  useEffect(() => {
    fetchEmployees(currentPage, rowsPerPage);
    fetchCustomFieldLabels();
  }, [currentPage, rowsPerPage, fetchEmployees, fetchCustomFieldLabels]);

  // Reset form
  const resetForm = () => {
    setEmployeeForm({
      name: "",
      email: "",
      countryCode: countries[0],
      phone_number: "",
      aadhar_number: "",
      address: "",
      city: "",
      state: "",
      country: null,
      role: null,
      joining_date: null,
      password: "",
    });
    setFormErrors({});
    setIsEditing(false);
    setEditingId(null);
    setEmployeeLabels([]);
  };

  // Open dialog for adding new employee
  const handleAddEmployee = () => {
    resetForm();
    setEmployeeLabels([]);
    setDialogVisible(true);
  };

  // View employee details
  const handleViewEmployee = (employee) => {
    setViewingEmployee(employee);
    setViewDialogVisible(true);
  };

  // Open dialog for editing employee
  const handleEditEmployee = (employee) => {
    const countryObj =
      countries.find((c) => c.name === employee.country) || countries[0];

    // Parse joining_date from dd/mm/yyyy to Date object
    let joiningDateObj = null;
    if (employee.joining_date) {
      const [day, month, year] = employee.joining_date.split("/");
      joiningDateObj = new Date(year, month - 1, day);
    }

    setEmployeeForm({
      name: employee.name,
      email: employee.email,
      countryCode: countryObj,
      phone_number: employee.phone_number,
      aadhar_number: employee.aadhar_number,
      address: employee.address,
      city: employee.city,
      state: employee.state,
      country: countries.find((c) => c.name === employee.country),
      role: employee.role,
      joining_date: joiningDateObj,
      password: "", // Don't load password when editing
    });
    setIsEditing(true);
    setEditingId(employee.emp_id);
    setDialogVisible(true);
    setFormErrors({});

    // Load custom_fields if present (convert from [{labelname: labelvalue}] to internal format)
    if (employee.custom_fields && Array.isArray(employee.custom_fields)) {
      setEmployeeLabels(
        employee.custom_fields.flatMap((fieldObj) =>
          Object.entries(fieldObj).map(([name, value]) => ({
            id: Date.now() + Math.random(),
            name,
            value,
            saved: true,
          }))
        )
      );
    } else {
      setEmployeeLabels([]);
    }
  };

  // Delete employee
  const handleDeleteEmployee = async (emp_id) => {
    try {
      setLoading(true);
      await api.delete(`/employees/${emp_id}`);

      toast.current?.show({
        severity: "success",
        summary: "Employee Deleted",
        detail: "Employee has been removed successfully",
        life: 3000,
      });

      // Refresh employee list and custom field labels from backend
      await fetchEmployees();
      await fetchCustomFieldLabels();
    } catch (error) {
      console.error("Error deleting employee:", error);
      const errorMessage =
        error.response?.data?.detail || "Failed to delete employee";
      toast.current?.show({
        severity: "error",
        summary: "Error",
        detail: errorMessage,
        life: 4000,
      });
    } finally {
      setLoading(false);
    }
  };

  // Save employee (add or update)
  const handleSaveEmployee = async () => {
    // Reset previous errors
    const errors = {};

    // Mandatory field validation: name, email, phone_number, role
    if (!employeeForm.name?.trim()) {
      errors.name = "Employee name is required";
    }

    if (!employeeForm.email?.trim()) {
      errors.email = "Email is required";
    } else {
      // Email format validation
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(employeeForm.email)) {
        errors.email = "Please enter a valid email address";
      }
    }

    if (!employeeForm.phone_number?.trim()) {
      errors.phone_number = "Phone number is required";
    }

    if (!employeeForm.role) {
      errors.role = "Role is required";
    }

    // Password required for new employees
    if (!isEditing && !employeeForm.password?.trim()) {
      errors.password = "Password is required for new employees";
    }

    // If there are errors, display them in the dialog
    if (Object.keys(errors).length > 0) {
      setFormErrors(errors);
      return;
    }

    // Clear errors if validation passes
    setFormErrors({});

    try {
      setLoading(true);

      // Format joining date from Calendar to dd/mm/yyyy
      const formattedJoiningDate = employeeForm.joining_date
        ? `${String(employeeForm.joining_date.getDate()).padStart(
            2,
            "0"
          )}/${String(employeeForm.joining_date.getMonth() + 1).padStart(
            2,
            "0"
          )}/${employeeForm.joining_date.getFullYear()}`
        : null;

      // Format custom fields from employeeLabels to array of {labelname: labelvalue}
      const customFields = employeeLabels
        .filter((l) => l.saved && l.name && l.value)
        .map((l) => ({ [l.name]: l.value }));

      console.log("Employee Form:", employeeForm);
      console.log("Role Value:", employeeForm.role);

      const employeeData = {
        name: employeeForm.name,
        email: employeeForm.email,
        phone_number: employeeForm.phone_number,
        aadhar_number: employeeForm.aadhar_number || null,
        address: employeeForm.address || null,
        city: employeeForm.city || null,
        state: employeeForm.state || null,
        country: employeeForm.country?.name || null,
        role: employeeForm.role,
        joining_date: formattedJoiningDate,
        custom_fields: customFields.length > 0 ? customFields : null,
      };

      console.log("Employee Data being sent:", employeeData);

      if (isEditing) {
        // Update existing employee
        if (!employeeForm.password?.trim()) {
          // If no password provided, don't include it in the update
          await api.put(`/employees/${editingId}`, employeeData);
        } else {
          // Include password if provided
          await api.put(`/employees/${editingId}`, {
            ...employeeData,
            password: employeeForm.password,
          });
        }

        toast.current?.show({
          severity: "success",
          summary: "Employee Updated",
          detail: `${employeeForm.name} has been updated successfully`,
          life: 3000,
        });
      } else {
        // Add new employee
        await api.post("/employees", {
          ...employeeData,
          password: employeeForm.password,
        });

        toast.current?.show({
          severity: "success",
          summary: "Employee Added",
          detail: `${employeeForm.name} has been added successfully`,
          life: 3000,
        });
      }

      // Refresh employee list and custom field labels from backend
      await fetchEmployees();
      await fetchCustomFieldLabels();

      setDialogVisible(false);
      resetForm();
    } catch (error) {
      console.error("Error saving employee:", error);

      let errorMessage = "Failed to save employee";

      // Handle validation errors from backend
      if (error.response?.data?.detail) {
        const detail = error.response.data.detail;
        if (Array.isArray(detail)) {
          // FastAPI validation errors
          errorMessage = detail
            .map((err) => `${err.loc.join(".")}: ${err.msg}`)
            .join(", ");
        } else if (typeof detail === "string") {
          errorMessage = detail;
        } else {
          errorMessage = JSON.stringify(detail);
        }
      }

      toast.current?.show({
        severity: "error",
        summary: "Error",
        detail: errorMessage,
        life: 5000,
      });
    } finally {
      setLoading(false);
    }
  };

  // Cancel dialog
  const handleCancel = () => {
    setDialogVisible(false);
    resetForm();
  };

  // Custom Labels helpers
  const addEmptyEmployeeLabel = () => {
    if (employeeLabels.some((l) => !l.saved)) return;
    setEmployeeLabels((prev) => [
      ...prev,
      { id: Date.now(), name: "", value: "", saved: false },
    ]);
  };

  const saveEmployeeLabel = (id) => {
    const label = employeeLabels.find((l) => l.id === id);
    if (!label || !label.name.trim() || !label.value.trim()) {
      toast.current?.show({
        severity: "warn",
        summary: "Invalid Input",
        detail: "Please fill in both label name and value.",
        life: 3000,
      });
      return;
    }

    // Check for duplicate label name
    const duplicate = employeeLabels.find(
      (l) =>
        l.id !== id &&
        l.saved &&
        l.name.trim().toLowerCase() === label.name.trim().toLowerCase()
    );
    if (duplicate) {
      toast.current?.show({
        severity: "error",
        summary: "Duplicate Label",
        detail: `Label name "${label.name}" already exists. Please use a different name.`,
        life: 3000,
      });
      return;
    }

    setEmployeeLabels((prev) =>
      prev.map((l) => (l.id === id ? { ...l, saved: true } : l))
    );
    toast.current?.show({
      severity: "success",
      summary: "Custom Field Saved",
      detail: `${label.name}: ${label.value}`,
      life: 2000,
    });
  };

  const removeEmployeeLabel = (id) => {
    setEmployeeLabels((prev) => prev.filter((l) => l.id !== id));
  };

  const updateEmployeeLabel = (id, field, value) => {
    setEmployeeLabels((prev) =>
      prev.map((l) => {
        if (l.id === id) {
          // If transitioning from saved to unsaved (editing), preserve original
          if (field === "saved" && value === false && l.saved) {
            return {
              ...l,
              [field]: value,
              originalName: l.name,
              originalValue: l.value,
            };
          }
          return { ...l, [field]: value };
        }
        return l;
      })
    );
  };

  const cancelEditEmployeeLabel = (id) => {
    setEmployeeLabels((prev) =>
      prev
        .map((l) => {
          if (l.id === id) {
            // If has original values, restore them; otherwise it's a new unsaved row, remove it
            if (l.originalName !== undefined && l.originalValue !== undefined) {
              return {
                ...l,
                name: l.originalName,
                value: l.originalValue,
                saved: true,
                originalName: undefined,
                originalValue: undefined,
              };
            }
            // New unsaved row - will be filtered out below
            return null;
          }
          return l;
        })
        .filter(Boolean)
    );
  };

  // Get value options for a specific label name
  const getLabelValueOptions = (labelName) => {
    if (!labelName) return [];

    // If predefined mapping exists, use it
    if (labelValueMappings[labelName]) {
      return labelValueMappings[labelName].map((v) => ({ label: v, value: v }));
    }

    // Otherwise, get values from existing employee custom_fields with this name
    const existingValues = [
      ...new Set(
        employees
          .flatMap((e) => e.custom_fields || [])
          .flatMap((fieldObj) =>
            Object.entries(fieldObj)
              .filter(([name]) => name === labelName)
              .map(([, value]) => value)
          )
          .filter(Boolean)
      ),
    ];

    return existingValues.map((v) => ({ label: v, value: v }));
  };

  // Custom Label Definition Dialog handlers
  const handleOpenCustomLabelDialog = () => {
    setNewLabelName("");
    setNewLabelValues([""]);
    setCustomLabelDialogVisible(true);
  };

  const handleAddLabelValue = () => {
    setNewLabelValues((prev) => [...prev, ""]);
  };

  const handleRemoveLabelValue = (index) => {
    setNewLabelValues((prev) => prev.filter((_, i) => i !== index));
  };

  const handleLabelValueChange = (index, value) => {
    setNewLabelValues((prev) => prev.map((v, i) => (i === index ? value : v)));
  };

  const handleSaveCustomLabel = () => {
    const trimmedName = newLabelName.trim();
    const validValues = newLabelValues
      .filter((v) => v.trim())
      .map((v) => v.trim());

    if (!trimmedName) {
      toast.current?.show({
        severity: "warn",
        summary: "Invalid Input",
        detail: "Please enter a label name.",
        life: 3000,
      });
      return;
    }

    if (validValues.length === 0) {
      toast.current?.show({
        severity: "warn",
        summary: "Invalid Input",
        detail: "Please add at least one label value.",
        life: 3000,
      });
      return;
    }

    // Check if label name already exists
    if (labelValueMappings[trimmedName]) {
      toast.current?.show({
        severity: "warn",
        summary: "Label Already Exists",
        detail: `Label "${trimmedName}" already exists. Values will be merged.`,
        life: 3000,
      });
    }

    // Add or update label mapping
    setLabelValueMappings((prev) => ({
      ...prev,
      [trimmedName]: [
        ...new Set([...(prev[trimmedName] || []), ...validValues]),
      ],
    }));

    toast.current?.show({
      severity: "success",
      summary: "Custom Label Added",
      detail: `Label "${trimmedName}" with ${validValues.length} value(s) has been added.`,
      life: 3000,
    });

    setCustomLabelDialogVisible(false);
  };

  const handleCancelCustomLabel = () => {
    setCustomLabelDialogVisible(false);
  };

  // Deprecated AutoComplete search methods (replaced by Dropdown filter)
  // const searchLabelName = (event) => { /* ... */ };
  // const searchLabelValue = (event) => { /* ... */ };

  // Since backend handles filtering, just use employees directly
  const filteredEmployees = employees;

  // Clear filters
  const handleClearFilters = () => {
    setFilterField(null);
    setFilterValue("");
    setCurrentPage(0); // Reset to first page
  };

  // Reset to page 0 when filter changes
  useEffect(() => {
    if (filterField || filterValue) {
      setCurrentPage(0);
    }
  }, [filterField, filterValue]);

  // Render employee card
  const renderEmployeeCard = (employee) => {
    return (
      <Card key={employee.emp_id} className="employee-card">
        <div className="employee-card-header">
          <div className="employee-avatar">
            <i className="pi pi-user"></i>
          </div>
          <div className="employee-basic-info">
            <h3 className="employee-name">{employee.name}</h3>
            <span className="employee-id">ID: {employee.emp_id}</span>
          </div>
          <Button
            icon="pi pi-eye"
            className="p-button-rounded p-button-text p-button-sm"
            onClick={() => handleViewEmployee(employee)}
            tooltip="View Details"
            tooltipOptions={{ position: "top" }}
          />
        </div>

        <div className="employee-card-body">
          <div className="employee-info-row">
            <i className="pi pi-envelope info-icon"></i>
            <span className="info-text">{employee.email}</span>
          </div>
          {employee.role && (
            <div className="employee-info-row">
              <i className="pi pi-briefcase info-icon"></i>
              <span className="info-text role-badge">{employee.role}</span>
            </div>
          )}
          {employee.joining_date && (
            <div className="employee-info-row">
              <i className="pi pi-calendar info-icon"></i>
              <span className="info-text">Joined: {employee.joining_date}</span>
            </div>
          )}
          <div className="employee-info-row">
            <i className="pi pi-phone info-icon"></i>
            <span className="info-text">{employee.phone_number}</span>
          </div>
        </div>

        <div className="employee-card-actions">
          <Button
            icon="pi pi-pencil"
            label="Edit"
            className="p-button-sm p-button-info"
            onClick={() => handleEditEmployee(employee)}
          />
          <Button
            icon="pi pi-trash"
            label="Delete"
            className="p-button-sm p-button-danger p-button-outlined"
            onClick={() => handleDeleteEmployee(employee.emp_id)}
          />
        </div>
      </Card>
    );
  };

  return (
    <>
      <Toast ref={toast} position="top-right" />

      {/* Add Employee Dialog */}
      <Dialog
        header={isEditing ? "Edit Employee" : "Add New Employee"}
        visible={dialogVisible}
        style={{ width: "95vw", maxWidth: "700px" }}
        onHide={handleCancel}
        draggable={false}
        resizable={false}
        blockScroll
        className="employee-dialog"
      >
        <div className="employee-dialog-content">
          {/* Display form errors at top of dialog */}
          {Object.keys(formErrors).length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded p-3 mb-3">
              <h4 className="text-red-800 font-semibold mb-2 text-sm">
                Please fix the following errors:
              </h4>
              <ul className="text-red-700 text-xs list-disc list-inside space-y-1">
                {Object.entries(formErrors).map(([field, error]) => (
                  <li key={field}>{error}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Employee Name */}
          <div className="flex flex-col gap-2">
            <label htmlFor="emp-name" className="text-[0.85rem] font-semibold">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <InputText
              id="emp-name"
              value={employeeForm.name}
              onChange={(e) => handleChange("name", e.target.value)}
              placeholder="Enter employee name"
              className={`w-full ${formErrors.name ? "p-invalid" : ""}`}
            />
          </div>

          {/* Employee Email */}
          <div className="flex flex-col gap-2">
            <label htmlFor="emp-email" className="text-[0.85rem] font-semibold">
              Employee Email <span className="text-red-500">*</span>
            </label>
            <InputText
              id="emp-email"
              type="email"
              value={employeeForm.email}
              onChange={(e) => handleChange("email", e.target.value)}
              placeholder="employee@example.com"
              className={`w-full ${formErrors.email ? "p-invalid" : ""}`}
            />
          </div>

          {/* Phone Number */}
          <div className="flex flex-col gap-2">
            <label htmlFor="emp-phone" className="text-[0.85rem] font-semibold">
              Phone Number <span className="text-red-500">*</span>
            </label>
            <InputText
              id="emp-phone"
              value={employeeForm.phone_number}
              onChange={(e) => handleChange("phone_number", e.target.value)}
              placeholder="Enter phone number"
              className={`w-full ${formErrors.phone_number ? "p-invalid" : ""}`}
            />
          </div>

          {/* Aadhar Number */}
          <div className="flex flex-col gap-2">
            <label
              htmlFor="emp-aadhar"
              className="text-[0.85rem] font-semibold"
            >
              Aadhar Number
            </label>
            <InputText
              id="emp-aadhar"
              value={employeeForm.aadhar_number}
              onChange={(e) => handleChange("aadhar_number", e.target.value)}
              placeholder="123456789012"
              maxLength="12"
              className="w-full"
            />
          </div>

          {/* Address */}
          <div className="flex flex-col gap-2">
            <label
              htmlFor="emp-address"
              className="text-[0.85rem] font-semibold"
            >
              Address
            </label>
            <InputText
              id="emp-address"
              value={employeeForm.address}
              onChange={(e) => handleChange("address", e.target.value)}
              placeholder="Street address"
              className="w-full"
            />
          </div>

          {/* City */}
          <div className="flex flex-col gap-2">
            <label htmlFor="emp-city" className="text-[0.85rem] font-semibold">
              City
            </label>
            <InputText
              id="emp-city"
              value={employeeForm.city}
              onChange={(e) => handleChange("city", e.target.value)}
              placeholder="City"
              className="w-full"
            />
          </div>

          {/* State */}
          <div className="flex flex-col gap-2">
            <label htmlFor="emp-state" className="text-[0.85rem] font-semibold">
              State
            </label>
            <InputText
              id="emp-state"
              value={employeeForm.state}
              onChange={(e) => handleChange("state", e.target.value)}
              placeholder="State"
              className="w-full"
            />
          </div>

          {/* Country */}
          <div className="flex flex-col gap-2">
            <label
              htmlFor="emp-country"
              className="text-[0.85rem] font-semibold"
            >
              Country
            </label>
            <Dropdown
              id="emp-country"
              value={employeeForm.country}
              options={countries}
              onChange={(e) => handleChange("country", e.value)}
              optionLabel="name"
              placeholder="Select country"
              className="w-full"
              filter
            />
          </div>

          {/* Role */}
          <div className="flex flex-col gap-2">
            <label htmlFor="emp-role" className="text-[0.85rem] font-semibold">
              Role <span className="text-red-500">*</span>
            </label>
            <Dropdown
              id="emp-role"
              value={employeeForm.role}
              options={roles}
              onChange={(e) => handleChange("role", e.value)}
              optionLabel="label"
              optionValue="value"
              placeholder="Select role"
              className={`w-full ${formErrors.role ? "p-invalid" : ""}`}
              filter
            />
            {formErrors.role && (
              <small className="text-red-500">{formErrors.role}</small>
            )}
          </div>

          {/* Joining Date */}
          <div className="flex flex-col gap-2">
            <label
              htmlFor="emp-joining-date"
              className="text-[0.85rem] font-semibold"
            >
              Joining Date (dd/mm/yyyy)
            </label>
            <Calendar
              id="emp-joining-date"
              value={employeeForm.joining_date}
              placeholder="Select joining date"
              onChange={(e) => handleChange("joining_date", e.value)}
              className="w-full"
              dateFormat="dd/mm/yy"
              touchUI
            />
          </div>

          {/* Password - Required for new employees */}
          {!isEditing && (
            <div className="flex flex-col gap-2">
              <label
                htmlFor="emp-password"
                className="text-[0.85rem] font-semibold"
              >
                Password <span className="text-red-500">*</span>
              </label>
              <InputText
                id="emp-password"
                type="password"
                value={employeeForm.password}
                onChange={(e) => handleChange("password", e.target.value)}
                placeholder="Enter password (min 8 characters)"
                className={`w-full ${formErrors.password ? "p-invalid" : ""}`}
              />
            </div>
          )}

          {/* Add Custom Label Definition Button (before Custom Fields) */}
          <div className="flex items-center gap-2 mb-2">
            <Button
              icon="pi pi-plus"
              label="Define Custom Label"
              size="small"
              severity="help"
              outlined
              onClick={handleOpenCustomLabelDialog}
              tooltip="Add a new custom label with predefined values"
              tooltipOptions={{ position: "top" }}
            />
          </div>

          {/* Custom Fields (Labels) under Joining Date */}
          <div className="bg-blue-100 p-4 pt-3 rounded">
            <div className="flex items-center justify-between">
              <label className="text-[1rem] font-bold">Custom Fields</label>
              <Button
                icon="pi pi-plus-circle"
                label="Add Field"
                size="small"
                severity="secondary"
                onClick={addEmptyEmployeeLabel}
              />
            </div>
            <div className="flex flex-col gap-2 mt-3">
              {employeeLabels.length === 0 && (
                <p className="text-[0.75rem] text-gray-600">
                  No custom fields added.
                </p>
              )}
              {employeeLabels.map((label) => (
                <div
                  key={label.id}
                  className="grid md:grid-cols-[1fr_1fr_auto] grid-cols-[1fr] gap-2 items-center bg-blue-50 p-3 rounded"
                >
                  {label.saved ? (
                    <>
                      <div className="col-span-2 text-sm font-semibold">
                        {label.name}:{" "}
                        <span className="font-normal">{label.value}</span>
                      </div>
                      <div className="flex gap-2 justify-end">
                        <Button
                          icon="pi pi-pencil"
                          rounded
                          severity="info"
                          className="w-6! h-6!"
                          onClick={() =>
                            updateEmployeeLabel(label.id, "saved", false)
                          }
                          tooltip="Edit"
                          tooltipOptions={{ position: "top" }}
                        />
                        <Button
                          icon="pi pi-trash"
                          rounded
                          severity="danger"
                          className="w-6! h-6!"
                          onClick={() => removeEmployeeLabel(label.id)}
                          tooltip="Delete"
                          tooltipOptions={{ position: "top" }}
                        />
                      </div>
                    </>
                  ) : (
                    <>
                      <div className="flex flex-col w-full">
                        <label className="text-[0.8rem] font-semibold mb-1">
                          Label Name
                        </label>
                        <Dropdown
                          value={label.name}
                          options={labelNameOptions}
                          onChange={(e) =>
                            updateEmployeeLabel(label.id, "name", e.value)
                          }
                          placeholder="Select label name"
                          className="w-full!"
                          filter
                          optionLabel="label"
                          optionValue="value"
                        />
                      </div>
                      <div className="flex flex-col w-full">
                        <label className="text-[0.8rem] font-semibold mb-1">
                          Label Value
                        </label>
                        <Dropdown
                          value={label.value}
                          options={getLabelValueOptions(label.name)}
                          onChange={(e) =>
                            updateEmployeeLabel(label.id, "value", e.value)
                          }
                          placeholder="Select or type label value"
                          className="w-full!"
                          filter
                          editable
                          optionLabel="label"
                          optionValue="value"
                        />
                      </div>
                      <div className="flex gap-2 justify-end">
                        <Button
                          icon="pi pi-check"
                          rounded
                          severity="success"
                          className="w-6! h-6!"
                          onClick={() => saveEmployeeLabel(label.id)}
                          tooltip="Save"
                          tooltipOptions={{ position: "top" }}
                        />
                        <Button
                          icon="pi pi-times"
                          rounded
                          severity="secondary"
                          className="w-6! h-6!"
                          onClick={() => cancelEditEmployeeLabel(label.id)}
                          tooltip="Cancel"
                          tooltipOptions={{ position: "top" }}
                        />
                      </div>
                    </>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Dialog Actions */}
          <div className="dialog-actions">
            <Button
              label="Cancel"
              severity="secondary"
              onClick={handleCancel}
              className="dialog-btn"
            />
            <Button
              label={isEditing ? "Update" : "Add"}
              severity="success"
              onClick={handleSaveEmployee}
              className="dialog-btn"
            />
          </div>
        </div>
      </Dialog>

      {/* Custom Label Definition Dialog */}
      <Dialog
        header="Add Custom Label"
        visible={customLabelDialogVisible}
        style={{ width: "95vw", maxWidth: "550px" }}
        onHide={handleCancelCustomLabel}
        draggable={false}
        resizable={false}
        blockScroll
        className="employee-dialog"
      >
        <div className="employee-dialog-content">
          {/* Label Name */}
          <div className="flex flex-col gap-2">
            <label className="text-[0.85rem] font-semibold">
              Label Name <span className="text-red-500">*</span>
            </label>
            <InputText
              value={newLabelName}
              onChange={(e) => setNewLabelName(e.target.value)}
              placeholder="e.g., Shirt Size, T-Shirt Size"
              className="w-full"
            />
          </div>

          {/* Label Values */}
          <div className="flex flex-col gap-2">
            <label className="text-[0.85rem] font-semibold">
              Label Values <span className="text-red-500">*</span>
            </label>
            {newLabelValues.map((value, index) => (
              <div key={index} className="flex gap-2 items-center">
                <InputText
                  value={value}
                  onChange={(e) =>
                    handleLabelValueChange(index, e.target.value)
                  }
                  placeholder={`Value ${index + 1}`}
                  className="flex-1"
                />
                <div className="flex gap-1">
                  {newLabelValues.length > 1 && (
                    <Button
                      icon="pi pi-trash"
                      rounded
                      text
                      severity="danger"
                      onClick={() => handleRemoveLabelValue(index)}
                      tooltip="Remove"
                      tooltipOptions={{ position: "top" }}
                      className="w-8! h-8! p-0! flex items-center justify-center hover:bg-red-50"
                      style={{ fontSize: "0.75rem" }}
                    />
                  )}
                  {index === newLabelValues.length - 1 && (
                    <Button
                      icon="pi pi-plus"
                      rounded
                      text
                      severity="success"
                      onClick={handleAddLabelValue}
                      tooltip="Add Value"
                      tooltipOptions={{ position: "top" }}
                      className="w-8! h-8! p-0! flex items-center justify-center hover:bg-green-50"
                      style={{ fontSize: "0.75rem" }}
                    />
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Dialog Actions */}
          <div className="dialog-actions">
            <Button
              label="Cancel"
              severity="secondary"
              onClick={handleCancelCustomLabel}
              className="dialog-btn"
            />
            <Button
              label="Add"
              severity="success"
              onClick={handleSaveCustomLabel}
              className="dialog-btn"
            />
          </div>
        </div>
      </Dialog>

      {/* Main Employees Screen */}
      <div className="employees-container">
        <div className="employees-header">
          <h2 className="text-2xl font-bold text-gray-800">
            Employee Management
          </h2>
          <Button
            label="Add Employee"
            icon="pi pi-plus"
            severity="success"
            onClick={handleAddEmployee}
            className="add-employee-btn"
          />
        </div>

        {/* Filter Section */}
        <div className="filter-section">
          <div className="filter-controls">
            <Dropdown
              value={filterField}
              options={getFilterOptions()}
              onChange={(e) => setFilterField(e.value)}
              optionLabel="label"
              optionValue="value"
              placeholder="Type or Select field to filter"
              className="filter-dropdown"
              filter
            />
            <InputText
              value={filterValue}
              onChange={(e) => setFilterValue(e.target.value)}
              placeholder={
                filterField
                  ? `Search by ${
                      getFilterOptions().find(
                        (opt) => opt.value === filterField
                      )?.label || ""
                    }`
                  : "Select a field first"
              }
              className="filter-input"
              disabled={!filterField}
            />
            <Button
              icon="pi pi-times"
              label="Clear"
              className="p-button-outlined p-button-secondary clear-filter-btn"
              onClick={handleClearFilters}
              disabled={!filterField && !filterValue}
            />
          </div>
          <div className="filter-results">
            <span className="results-count">
              {loading ? (
                "Loading..."
              ) : totalRecords === 0 ? (
                "No employees found"
              ) : (
                <>
                  Showing {currentPage * rowsPerPage + 1}-
                  {Math.min((currentPage + 1) * rowsPerPage, totalRecords)} of{" "}
                  {totalRecords} employee(s)
                  {filterField && filterValue && " (filtered)"}
                </>
              )}
            </span>
          </div>
        </div>

        {/* Employees Grid */}
        <div className="employees-grid-wrapper">
          {loading ? (
            <div className="empty-state">
              <i
                className="pi pi-spin pi-spinner"
                style={{ fontSize: "3rem", color: "#4CAF50" }}
              ></i>
              <p>Loading employees...</p>
            </div>
          ) : filteredEmployees.length === 0 ? (
            <div className="empty-state">
              <i
                className="pi pi-users"
                style={{ fontSize: "3rem", color: "#ccc" }}
              ></i>
              <p>
                {employees.length === 0
                  ? 'No employees found. Click "Add Employee" to get started.'
                  : "No employees match the filter criteria."}
              </p>
            </div>
          ) : (
            <div className="employees-grid">
              {filteredEmployees.map((employee) => (
                <div key={employee.emp_id}>{renderEmployeeCard(employee)}</div>
              ))}
            </div>
          )}

          {/* Pagination */}
          {!loading && filteredEmployees.length > 0 && (
            <div className="mt-4">
              <Paginator
                first={currentPage * rowsPerPage}
                rows={rowsPerPage}
                totalRecords={totalRecords}
                rowsPerPageOptions={[10, 20, 50, 100]}
                onPageChange={(e) => {
                  setCurrentPage(e.page);
                  setRowsPerPage(e.rows);
                }}
              />
            </div>
          )}
        </div>
      </div>

      {/* View Employee Details Dialog */}
      <Dialog
        header="Employee Details"
        visible={viewDialogVisible}
        style={{ width: "95vw", maxWidth: "600px" }}
        onHide={() => setViewDialogVisible(false)}
        draggable={false}
        resizable={false}
      >
        {viewingEmployee && (
          <div className="employee-details-view p-4">
            <div className="flex flex-col gap-4">
              {/* Header with avatar and basic info */}
              <div className="flex items-center gap-4 pb-4 border-b">
                <div className="employee-avatar-large flex items-center justify-center bg-blue-100 rounded-full w-20 h-20">
                  <i className="pi pi-user text-4xl text-blue-600"></i>
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-gray-800">
                    {viewingEmployee.name}
                  </h2>
                  <p className="text-gray-600">ID: {viewingEmployee.emp_id}</p>
                  {viewingEmployee.role && (
                    <span className="inline-block mt-1 px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm font-semibold">
                      {viewingEmployee.role}
                    </span>
                  )}
                </div>
              </div>

              {/* Contact Information */}
              <div>
                <h3 className="text-lg font-semibold text-gray-700 mb-3">
                  Contact Information
                </h3>
                <div className="grid gap-3">
                  <div className="flex items-center gap-3">
                    <i className="pi pi-envelope text-gray-500"></i>
                    <span className="text-gray-700">
                      {viewingEmployee.email}
                    </span>
                  </div>
                  <div className="flex items-center gap-3">
                    <i className="pi pi-phone text-gray-500"></i>
                    <span className="text-gray-700">
                      {viewingEmployee.phone_number}
                    </span>
                  </div>
                  {viewingEmployee.aadhar_number && (
                    <div className="flex items-center gap-3">
                      <i className="pi pi-id-card text-gray-500"></i>
                      <span className="text-gray-700">
                        {viewingEmployee.aadhar_number}
                      </span>
                    </div>
                  )}
                </div>
              </div>

              {/* Address Information */}
              {(viewingEmployee.address ||
                viewingEmployee.city ||
                viewingEmployee.state ||
                viewingEmployee.country) && (
                <div>
                  <h3 className="text-lg font-semibold text-gray-700 mb-3">
                    Address
                  </h3>
                  <div className="flex items-start gap-3">
                    <i className="pi pi-map-marker text-gray-500 mt-1"></i>
                    <div className="text-gray-700">
                      {viewingEmployee.address && (
                        <div>{viewingEmployee.address}</div>
                      )}
                      <div>
                        {[
                          viewingEmployee.city,
                          viewingEmployee.state,
                          viewingEmployee.country,
                        ]
                          .filter(Boolean)
                          .join(", ")}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Employment Details */}
              {viewingEmployee.joining_date && (
                <div>
                  <h3 className="text-lg font-semibold text-gray-700 mb-3">
                    Employment Details
                  </h3>
                  <div className="flex items-center gap-3">
                    <i className="pi pi-calendar text-gray-500"></i>
                    <span className="text-gray-700">
                      Joined: {viewingEmployee.joining_date}
                    </span>
                  </div>
                </div>
              )}

              {/* Custom Fields - Show data only, no labels */}
              {viewingEmployee.custom_fields &&
                viewingEmployee.custom_fields.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-700 mb-3">
                      Additional Information
                    </h3>
                    <div className="grid gap-2">
                      {viewingEmployee.custom_fields.map((field, idx) => {
                        const [labelName, labelValue] =
                          Object.entries(field)[0];
                        return (
                          <div
                            key={idx}
                            className="flex items-center gap-3 bg-gray-50 p-2 rounded"
                          >
                            <i className="pi pi-info-circle text-gray-500"></i>
                            <div>
                              <span className="text-sm font-medium text-gray-600">
                                {labelName}:{" "}
                              </span>
                              <span className="text-gray-700">
                                {labelValue}
                              </span>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
            </div>
          </div>
        )}
      </Dialog>
    </>
  );
}
